services:
  rtml:
    build: "./docker/rtmp"
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  obs:
    build: "./docker/obs"
    container_name: obs_server
    volumes: 
      - ./packages/prisma-schema:/app/prisma-schema
