services:
  rtml:
    build: "./docker/rtmp"
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  obs:
    build: "./docker/obs"
    container_name: obs_server
    environment:
      - DATABASE_URL=postgresql://callmenikk:1234@host.docker.internal:9900/stritch
      - NEXTAUTH_SECRET=iknasd*8sda7HUJAD7sda
      - ORIGIN_CORS=http://localhost:3000
    ports:
      - "8000:8000"
      - "9901:9900"
