import "@stream-m3u8/ui/globals.css";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { TRPCReactProvider } from "../trpc/react";

export const metadata: Metadata = {
  title: "stream-m3u8",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body style={GeistSans.style}>
        <TRPCReactProvider>
          <div className="container">{children}</div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
